[package]
name = "umiserver"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
actix = "0.13.5"
serde = {version = "1.0.215", features=["serde_derive"]}
actix-web-actors = "4"
serde_json = "1.0" 
uuid = {version = "1.11.0", features=["v4"]}
lazy_static = "1.4"